import type { QuoteLocation, VerificationStatus } from '@/core/review/types';
import { useLocale } from '@/state/locale.store';

/** Textos do texto completo em PDF e das evidências — à parte de `copy.ts` pelo mesmo critério dele. */
export const EVIDENCE_COPY = {
  pt: {
    fullText: 'Texto completo',
    attach: 'Anexar PDF',
    replace: 'Trocar PDF',
    remove: 'Remover PDF',
    removeConfirm: 'Remover o PDF deste estudo?',
    removeHint: 'As evidências continuam salvas com o texto citado; ao anexar o PDF de novo, os destaques voltam.',
    cancel: 'Cancelar',
    openReader: 'Abrir leitor e evidências',
    pages: '{n} p.',
    reading: 'Lendo o PDF…',
    missingFile:
      'O PDF deste estudo não está neste navegador (o projeto foi aberto em outro lugar ou o arquivo foi removido). Anexe o arquivo de novo: o mesmo PDF é reconhecido pelo conteúdo.',
    scanned:
      'PDF escaneado: não há texto para selecionar nem para a IA ler. Marque áreas da página como evidência ou use um PDF com texto (passado por OCR).',
    partial: 'Algumas páginas não têm texto (figuras ou tabelas em imagem): nelas, marque áreas em vez de trechos.',
    notPdf: 'O arquivo não é um PDF.',
    readFailed: 'Não foi possível ler o PDF: {error}',
    noPdfYet: 'Sem PDF anexado.',

    // Lote e piloto
    blockTitle: 'Textos completos e evidências',
    blockHint:
      'Anexe o PDF de cada estudo e ligue cada resposta ao trecho do artigo que a sustenta. Os PDFs ficam só neste navegador, fora do arquivo do projeto.',
    bulk: 'Enviar PDFs em lote',
    bulkWorking: 'Lendo {done} de {total}…',
    bulkResult: '{matched} de {total} PDFs ligados aos estudos pelo DOI ou pelo título.',
    bulkUnmatched: 'Sem estudo correspondente — escolha a qual estudo pertence:',
    bulkPick: 'Escolher estudo…',
    exportCsv: 'Exportar evidências (CSV)',
    storage: '{used} usados no navegador',
    metrics: {
      withPdf: 'Estudos com PDF',
      scanned: 'Escaneados',
      answersWithEvidence: 'Respostas com evidência',
      suggested: 'Propostas da IA',
      confirmed: 'Confirmadas',
      edited: 'Corrigidas',
      rejected: 'Rejeitadas',
      pending: 'Aguardando conferência',
      aiQuotes: 'Trechos citados pela IA',
      located: 'Achados no PDF',
      notFound: 'Não localizados',
    },
    metricsHint:
      'Números do piloto: quanto a IA acertou (confirmadas), errou em parte (corrigidas) ou errou (rejeitadas), e quantos trechos citados por ela existem de fato no PDF.',

    // Leitor
    readerTitle: 'Leitor e evidências',
    zoomIn: 'Aumentar',
    zoomOut: 'Diminuir',
    fitWidth: 'Ajustar à largura',
    page: 'Página',
    areaMode: 'Marcar área',
    areaModeHint: 'Arraste sobre a página para marcar uma tabela ou figura como evidência de «{target}».',
    textModeHint: 'Selecione um trecho no PDF para ligá-lo a «{target}».',
    noTarget: 'Escolha à direita a pergunta que o trecho vai sustentar.',
    useSelection: 'Usar como evidência de «{target}»',
    areaLabel: 'Área da página',
    questions: 'Perguntas',
    activeHint: 'Pergunta ativa — os trechos que você marcar vão para ela.',
    evidenceCount: '{n} trecho(s)',
    noEvidence: 'Sem trecho ligado.',
    goTo: 'Ir ao trecho',
    removeEvidence: 'Remover trecho',
    origin: { manual: 'Marcado por você', ai: 'Citado pela IA' },
    location: {
      exact: 'Achado no PDF',
      approximate: 'Achado (aproximado)',
      'not-found': 'Não localizado no PDF',
    } satisfies Record<QuoteLocation, string>,
    locationHint: {
      exact: 'O trecho citado está no PDF, palavra por palavra.',
      approximate: 'O começo e o fim do trecho estão no PDF; o meio difere um pouco. Confira.',
      'not-found': 'A IA citou um texto que não está no PDF — pode ter sido inventado. Não dá para aceitar a resposta como veio: marque o trecho certo ou corrija a resposta.',
    } satisfies Record<QuoteLocation, string>,
    status: {
      suggested: 'Aguardando conferência',
      confirmed: 'Confirmada',
      edited: 'Corrigida',
      rejected: 'Rejeitada',
      manual: 'Resposta manual',
    } satisfies Record<VerificationStatus, string>,
    aiSuggests: 'A IA sugere',
    accept: 'Aceitar',
    reject: 'Rejeitar',
    acceptBlocked: 'Nenhum trecho citado pela IA foi achado no PDF. Marque o trecho certo ou corrija a resposta.',
    yourAnswer: 'Sua resposta',
    exclusionTarget: 'Motivo de exclusão do texto completo',
    exclusionNone: 'Sem exclusão decidida — decida na triagem; aqui você liga o motivo ao trecho.',

    // IA
    aiRun: 'Propor respostas com IA',
    aiRerun: 'Propor de novo com IA',
    aiRunning: 'A IA está lendo o artigo…',
    aiDisclosure: 'Envia o texto deste PDF (≈ {chars} caracteres{refs}) para {provider} · {model}, {route}.',
    aiRefsDropped: ', sem as referências',
    aiRouteOwn: 'com a sua chave, direto do navegador',
    aiRouteServer: 'pelo servidor do Simetrics (conta como 1 pergunta gratuita do Simi)',
    aiConfirmTitle: 'Enviar o texto do artigo para a IA?',
    aiConfirmBody:
      'O texto completo deste PDF (≈ {chars} caracteres{refs}) vai para {provider} · {model}, {route}. O provedor processa o conteúdo segundo os termos dele. A IA só propõe: nada entra na revisão sem a sua conferência.',
    aiConfirm: 'Enviar e propor',
    aiTruncated: 'O artigo passou do limite e foi enviado até o caractere {chars}.',
    aiNoText: 'Este PDF não tem texto para a IA ler (escaneado).',
    aiNoQuestions: 'Não há perguntas para a IA: defina o formulário de extração ou o checklist de qualidade no protocolo.',
    aiDone: '{n} resposta(s) proposta(s). Confira cada uma ao lado do trecho.',
    aiNothing: 'A IA não achou no artigo resposta para as perguntas.',
    aiFailed: 'A IA falhou: {error}',
    aiDiscarded: '{n} resposta(s) descartada(s) por não caber no tipo do campo.',
    aiReadonly: 'No exemplo (só visualização), a IA não é chamada.',
    aiUnavailable:
      'A IA gratuita não está disponível neste servidor. Configure sua própria chave em "Configurar IA" (a mesma do Simi) para propor respostas.',
  },
  en: {
    fullText: 'Full text',
    attach: 'Attach PDF',
    replace: 'Replace PDF',
    remove: 'Remove PDF',
    removeConfirm: 'Remove this study’s PDF?',
    removeHint: 'Evidence stays saved with the quoted text; attach the PDF again and the highlights come back.',
    cancel: 'Cancel',
    openReader: 'Open reader and evidence',
    pages: '{n} pp.',
    reading: 'Reading the PDF…',
    missingFile:
      'This study’s PDF is not in this browser (the project was opened elsewhere or the file was removed). Attach the file again: the same PDF is recognized by its content.',
    scanned:
      'Scanned PDF: there is no text to select or for the AI to read. Mark page areas as evidence, or use a PDF with text (run through OCR).',
    partial: 'Some pages have no text (figures or tables as images): mark areas there instead of quotes.',
    notPdf: 'The file is not a PDF.',
    readFailed: 'Could not read the PDF: {error}',
    noPdfYet: 'No PDF attached.',

    blockTitle: 'Full texts and evidence',
    blockHint:
      'Attach each study’s PDF and link every answer to the passage of the article that supports it. PDFs stay in this browser only, outside the project file.',
    bulk: 'Upload PDFs in bulk',
    bulkWorking: 'Reading {done} of {total}…',
    bulkResult: '{matched} of {total} PDFs linked to studies by DOI or title.',
    bulkUnmatched: 'No matching study — choose which study it belongs to:',
    bulkPick: 'Choose a study…',
    exportCsv: 'Export evidence (CSV)',
    storage: '{used} used in the browser',
    metrics: {
      withPdf: 'Studies with PDF',
      scanned: 'Scanned',
      answersWithEvidence: 'Answers with evidence',
      suggested: 'AI proposals',
      confirmed: 'Confirmed',
      edited: 'Corrected',
      rejected: 'Rejected',
      pending: 'Awaiting check',
      aiQuotes: 'Quotes cited by the AI',
      located: 'Found in the PDF',
      notFound: 'Not found',
    },
    metricsHint:
      'Pilot numbers: how often the AI was right (confirmed), partly wrong (corrected) or wrong (rejected), and how many of its quotes actually exist in the PDF.',

    readerTitle: 'Reader and evidence',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fitWidth: 'Fit width',
    page: 'Page',
    areaMode: 'Mark area',
    areaModeHint: 'Drag over the page to mark a table or figure as evidence for “{target}”.',
    textModeHint: 'Select a passage in the PDF to link it to “{target}”.',
    noTarget: 'Choose on the right the question the passage will support.',
    useSelection: 'Use as evidence for “{target}”',
    areaLabel: 'Page area',
    questions: 'Questions',
    activeHint: 'Active question — passages you mark go to it.',
    evidenceCount: '{n} passage(s)',
    noEvidence: 'No passage linked.',
    goTo: 'Go to passage',
    removeEvidence: 'Remove passage',
    origin: { manual: 'Marked by you', ai: 'Quoted by the AI' },
    location: {
      exact: 'Found in the PDF',
      approximate: 'Found (approximate)',
      'not-found': 'Not found in the PDF',
    } satisfies Record<QuoteLocation, string>,
    locationHint: {
      exact: 'The quoted passage is in the PDF, word for word.',
      approximate: 'The start and end of the passage are in the PDF; the middle differs a little. Check it.',
      'not-found': 'The AI quoted text that is not in the PDF — it may be made up. The answer cannot be accepted as is: mark the right passage or correct the answer.',
    } satisfies Record<QuoteLocation, string>,
    status: {
      suggested: 'Awaiting check',
      confirmed: 'Confirmed',
      edited: 'Corrected',
      rejected: 'Rejected',
      manual: 'Manual answer',
    } satisfies Record<VerificationStatus, string>,
    aiSuggests: 'The AI suggests',
    accept: 'Accept',
    reject: 'Reject',
    acceptBlocked: 'None of the AI’s quotes was found in the PDF. Mark the right passage or correct the answer.',
    yourAnswer: 'Your answer',
    exclusionTarget: 'Full-text exclusion reason',
    exclusionNone: 'No exclusion decided — decide it in screening; here you link the reason to a passage.',

    aiRun: 'Propose answers with AI',
    aiRerun: 'Propose again with AI',
    aiRunning: 'The AI is reading the article…',
    aiDisclosure: 'Sends this PDF’s text (≈ {chars} characters{refs}) to {provider} · {model}, {route}.',
    aiRefsDropped: ', without the references',
    aiRouteOwn: 'with your own key, straight from the browser',
    aiRouteServer: 'through the Simetrics server (counts as 1 free Simi question)',
    aiConfirmTitle: 'Send the article text to the AI?',
    aiConfirmBody:
      'The full text of this PDF (≈ {chars} characters{refs}) goes to {provider} · {model}, {route}. The provider processes it under its own terms. The AI only proposes: nothing enters the review without your check.',
    aiConfirm: 'Send and propose',
    aiTruncated: 'The article exceeded the limit and was sent up to character {chars}.',
    aiNoText: 'This PDF has no text for the AI to read (scanned).',
    aiNoQuestions: 'There are no questions for the AI: set up the extraction form or the quality checklist in the protocol.',
    aiDone: '{n} answer(s) proposed. Check each one next to its passage.',
    aiNothing: 'The AI found no answer to the questions in the article.',
    aiFailed: 'The AI failed: {error}',
    aiDiscarded: '{n} answer(s) discarded for not fitting the field type.',
    aiReadonly: 'In the example (view only), the AI is not called.',
    aiUnavailable: 'The free AI is not available on this server. Set your own key in "AI settings" (the same as Simi) to propose answers.',
  },
};

export type EvidenceCopy = (typeof EVIDENCE_COPY)['pt'];

export function useEvidenceCopy(): EvidenceCopy {
  return EVIDENCE_COPY[useLocale((state) => state.locale) === 'en' ? 'en' : 'pt'];
}

export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}
