/**
 * Textos da classificação híbrida. Ficam juntos aqui, e não em i18n/translations.ts,
 * porque são muitos e só esta funcionalidade os usa — o mesmo critério do
 * AiSettingsModal, que resolve os textos locais no próprio componente.
 */
export const HYBRID_COPY = {
  pt: {
    title: 'Classificação híbrida',
    subtitle: 'DeepSeek descobre as categorias · Jev classifica a base',
    description:
      'Uma amostra estratificada (agrupamentos do k-means × período + documentos atípicos) vai ao modelo gerativo, que propõe as categorias. Você revisa, o Jev classifica a amostra para medir a concordância entre os dois modelos, e só então a base inteira — com confiança calibrada por documento.',
    settings: 'Configurar',
    focusLabel: 'Foco da pesquisa (opcional)',
    focusPlaceholder: 'ex.: aplicações de aprendizado de máquina em saúde pública',
    discover: 'Descobrir categorias e classificar',
    manual: 'Definir categorias manualmente',
    missingGenerative: 'Informe a chave do modelo gerativo (DeepSeek) nas configurações para descobrir categorias.',
    missingJev: 'Jev indisponível: o servidor não tem TYPESAFE_API_KEY. Informe uma chave do Jev nas configurações.',
    jevFree: 'Classificação pelo Jev: gratuita e sem limite.',
    freeDiscovery: 'Descoberta gratuita (DeepSeek do Simetrics): restam {remaining} de {limit} classificações neste dispositivo.',
    freeDiscoveryExhausted:
      'As {limit} classificações gratuitas deste dispositivo acabaram. Informe sua chave do modelo gerativo, ou defina as categorias manualmente (o Jev continua livre).',
    apiKeyOptional: 'Chave de API (opcional)',
    generativeKeyHint: 'Sem chave própria, a descoberta usa o DeepSeek do Simetrics, com cota gratuita por dispositivo.',
    jevKeyHint: 'Sem chave própria, o Jev do Simetrics é livre.',
    privacy:
      'Título, palavras-chave e resumo dos documentos saem do navegador: a amostra vai ao modelo gerativo, e cada documento vai ao Jev (via proxy, porque a API do Jev não aceita chamadas diretas do navegador).',
    cancel: 'Cancelar',
    reviewTitle: 'Revise as categorias',
    reviewHint:
      'Ajuste nomes e descrições antes de classificar. "O que é" e "o que não é" em inglês dão mais acurácia ao Jev; a categoria "Outros" é incluída automaticamente.',
    manualHint:
      'Defina as categorias da sua pesquisa (ex.: critérios de uma revisão sistemática). Sem o modelo gerativo não há validação na amostra: o Jev classifica a base direto.',
    name: 'Nome',
    what: 'O que é (inglês)',
    notFor: 'O que não é (inglês)',
    examples: 'Exemplos da amostra',
    inSample: 'na amostra',
    addCategory: 'Adicionar categoria',
    removeCategory: 'Remover categoria',
    confirm: 'Validar e classificar a base',
    confirmManual: 'Classificar a base',
    resultTitle: 'Resultado da classificação híbrida',
    agreement: 'Concordância na amostra',
    kappa: 'κ de Cohen',
    auto: 'Aceitos',
    review: 'Revisar',
    unclassified: 'Não classificados',
    notMeasured: 'não medida',
    category: 'Categoria',
    documents: 'Docs',
    share: '%',
    meanConfidence: 'Confiança média',
    sampleAgreement: 'Concordância',
    methods: 'Texto de métodos',
    copy: 'Copiar',
    copied: 'Copiado',
    history: 'Versões da taxonomia',
    categoryUnit: 'categoria',
    categoryUnitPlural: 'categorias',
    origin: {
      discovery: 'descoberta',
      clarify: 'esclarecimento',
      expand: 'expansão',
      manual: 'manual',
      'user-edit': 'edição do usuário',
    },
    usage: 'Consumo',
    requests: 'requisições',
    tokens: 'tokens',
    dismiss: 'Fechar',
    // Configurações
    settingsTitle: 'Configurar classificação híbrida',
    settingsSubtitle: 'As chaves ficam só no armazenamento local deste navegador.',
    generativeSection: 'Modelo gerativo (descoberta)',
    jevSection: 'Jev (classificação)',
    apiKey: 'Chave de API',
    showKey: 'Mostrar chave',
    model: 'Modelo',
    baseUrl: 'URL base (compatível com OpenAI)',
    thresholdsSection: 'Limiares de confiança',
    accept: 'Aceitar automaticamente a partir de',
    reviewBelow: 'Não classificar abaixo de',
    advanced: 'Parâmetros',
    sampleSize: 'Tamanho da amostra',
    maxCategories: 'Máximo de categorias',
    reviewBefore: 'Revisar categorias antes de classificar',
    clarifyRounds: 'Rodadas de esclarecimento',
    expansionRounds: 'Rodadas de expansão',
    leftoverTrigger: 'Expandir quando as sobras passarem de (%)',
    concurrency: 'Requisições simultâneas ao Jev',
    test: 'Testar',
    testing: 'Testando…',
    testOk: 'Conexão OK',
    save: 'Salvar',
    clearKeys: 'Remover chaves',
  },
  en: {
    title: 'Hybrid classification',
    subtitle: 'DeepSeek discovers the categories · Jev classifies the corpus',
    description:
      'A stratified sample (k-means clusters × period + atypical documents) goes to the generative model, which proposes the categories. You review them, Jev classifies the sample to measure agreement between the two models, and only then the whole corpus — with calibrated confidence per document.',
    settings: 'Configure',
    focusLabel: 'Study focus (optional)',
    focusPlaceholder: 'e.g. machine learning applications in public health',
    discover: 'Discover categories and classify',
    manual: 'Define categories manually',
    missingGenerative: 'Set the generative model (DeepSeek) key in the settings to discover categories.',
    missingJev: 'Jev unavailable: the server has no TYPESAFE_API_KEY. Set a Jev key in the settings.',
    jevFree: 'Classification by Jev: free and unlimited.',
    freeDiscovery: 'Free discovery (Simetrics DeepSeek): {remaining} of {limit} classifications left on this device.',
    freeDiscoveryExhausted:
      'The {limit} free classifications on this device are used up. Set your generative model key, or define the categories manually (Jev stays free).',
    apiKeyOptional: 'API key (optional)',
    generativeKeyHint: 'Without your own key, discovery uses the Simetrics DeepSeek with a free per-device quota.',
    jevKeyHint: 'Without your own key, the Simetrics Jev is free.',
    privacy:
      'Document titles, keywords and abstracts leave the browser: the sample goes to the generative model, and each document goes to Jev (through a proxy, because the Jev API does not accept direct browser calls).',
    cancel: 'Cancel',
    reviewTitle: 'Review the categories',
    reviewHint:
      'Adjust names and descriptions before classifying. English "what" and "not for" give Jev better accuracy; the "Other" category is added automatically.',
    manualHint:
      'Define your study categories (e.g. systematic review criteria). Without the generative model there is no sample validation: Jev classifies the corpus directly.',
    name: 'Name',
    what: 'What it is (English)',
    notFor: 'What it is not (English)',
    examples: 'Sample examples',
    inSample: 'in sample',
    addCategory: 'Add category',
    removeCategory: 'Remove category',
    confirm: 'Validate and classify corpus',
    confirmManual: 'Classify corpus',
    resultTitle: 'Hybrid classification result',
    agreement: 'Sample agreement',
    kappa: "Cohen's κ",
    auto: 'Accepted',
    review: 'Review',
    unclassified: 'Unclassified',
    notMeasured: 'not measured',
    category: 'Category',
    documents: 'Docs',
    share: '%',
    meanConfidence: 'Mean confidence',
    sampleAgreement: 'Agreement',
    methods: 'Methods text',
    copy: 'Copy',
    copied: 'Copied',
    history: 'Taxonomy versions',
    categoryUnit: 'category',
    categoryUnitPlural: 'categories',
    origin: {
      discovery: 'discovery',
      clarify: 'clarification',
      expand: 'expansion',
      manual: 'manual',
      'user-edit': 'user edit',
    },
    usage: 'Usage',
    requests: 'requests',
    tokens: 'tokens',
    dismiss: 'Close',
    settingsTitle: 'Configure hybrid classification',
    settingsSubtitle: 'Keys are stored only in this browser’s local storage.',
    generativeSection: 'Generative model (discovery)',
    jevSection: 'Jev (classification)',
    apiKey: 'API key',
    showKey: 'Show key',
    model: 'Model',
    baseUrl: 'Base URL (OpenAI-compatible)',
    thresholdsSection: 'Confidence thresholds',
    accept: 'Accept automatically from',
    reviewBelow: 'Leave unclassified below',
    advanced: 'Parameters',
    sampleSize: 'Sample size',
    maxCategories: 'Maximum categories',
    reviewBefore: 'Review categories before classifying',
    clarifyRounds: 'Clarification rounds',
    expansionRounds: 'Expansion rounds',
    leftoverTrigger: 'Expand when leftovers exceed (%)',
    concurrency: 'Concurrent Jev requests',
    test: 'Test',
    testing: 'Testing…',
    testOk: 'Connection OK',
    save: 'Save',
    clearKeys: 'Remove keys',
  },
} as const;

export type HybridCopy = (typeof HYBRID_COPY)[keyof typeof HYBRID_COPY];
