import type { Framework, ReviewType } from '@/core/review/types';

/**
 * Textos da revisão sistematizada. Ficam juntos aqui, e não em i18n/translations.ts,
 * pelo mesmo critério da classificação híbrida: são muitos e só este módulo os usa.
 */
export const REVIEW_COPY = {
  pt: {
    eyebrow: 'Revisão sistematizada',
    intro:
      'Planeje o protocolo, faça a triagem da base importada em duas etapas, avalie a qualidade e extraia os dados dos estudos incluídos, e gere a síntese, o fluxo PRISMA e o relatório. Tudo fica salvo no projeto, no seu navegador.',
    steps: {
      protocol: 'Protocolo',
      screening: 'Triagem',
      quality: 'Qualidade',
      extraction: 'Extração',
      synthesis: 'Síntese',
      prisma: 'PRISMA e relatório',
    },

    // Protocolo
    typeLabel: 'Tipo de revisão',
    types: {
      systematic: 'Revisão sistemática',
      scoping: 'Revisão de escopo',
      integrative: 'Revisão integrativa',
      rapid: 'Revisão rápida',
      umbrella: 'Revisão guarda-chuva',
      mapping: 'Mapeamento sistemático',
      other: 'Outra revisão sistematizada',
    } satisfies Record<ReviewType, string>,
    typeHints: {
      systematic: 'Pergunta focada, busca exaustiva, avaliação da qualidade dos estudos e síntese.',
      scoping: 'Mapeia a extensão e a natureza da evidência; avaliação de qualidade é opcional.',
      integrative: 'Combina estudos experimentais e não experimentais para compreender um fenômeno.',
      rapid: 'Etapas simplificadas para responder em prazo curto, com as simplificações declaradas.',
      umbrella: 'Revisão de revisões: sintetiza revisões sistemáticas existentes.',
      mapping: 'Classifica a literatura de um campo amplo, comum em engenharia de software.',
      other: 'Outro formato com método explícito e reprodutível.',
    } satisfies Record<ReviewType, string>,
    guideline: 'Diretriz de relato sugerida',
    titleLabel: 'Título da revisão',
    titlePlaceholder: 'ex.: Telessaúde para idosos com doenças crônicas',
    objectiveLabel: 'Objetivo',
    objectivePlaceholder: 'O que a revisão pretende responder ou mapear',
    frameworkLabel: 'Estrutura da pergunta',
    frameworks: {
      PICO: 'PICO',
      PICOC: 'PICOC',
      PCC: 'PCC',
      SPIDER: 'SPIDER',
      none: 'Nenhuma',
    } satisfies Record<Framework, string>,
    frameworkFields: {
      population: 'População',
      intervention: 'Intervenção',
      comparison: 'Comparação',
      outcome: 'Desfecho',
      context: 'Contexto',
      concept: 'Conceito',
      sample: 'Amostra',
      phenomenon: 'Fenômeno de interesse',
      design: 'Desenho',
      evaluation: 'Avaliação',
      researchType: 'Tipo de pesquisa',
    } as Record<string, string>,
    questionsLabel: 'Perguntas de pesquisa',
    questionPlaceholder: 'Pergunta de pesquisa',
    addQuestion: 'Adicionar pergunta',
    conceptsLabel: 'Conceitos e sinônimos da busca',
    conceptsHint:
      'Sinônimos de um conceito se unem por OR; conceitos entre si, por AND. Separe os termos por vírgula ou Enter. Use * como curinga (ex.: telemedicin*).',
    conceptLabelPlaceholder: 'Conceito (ex.: População)',
    termsPlaceholder: 'Adicionar termo e Enter',
    addConcept: 'Adicionar conceito',
    removeTerm: 'Remover termo',
    searchStringLabel: 'String de busca por base',
    searchStringEmpty: 'Adicione conceitos com termos para gerar a string.',
    genericTarget: 'Genérica',
    copy: 'Copiar',
    copied: 'Copiado',
    criteriaLabel: 'Critérios de elegibilidade',
    inclusion: 'Inclusão',
    exclusion: 'Exclusão',
    criterionPlaceholder: 'Descreva o critério',
    addInclusion: 'Critério de inclusão',
    addExclusion: 'Critério de exclusão',
    exclusionHint: 'Os critérios de exclusão viram os motivos de exclusão na triagem e no diagrama PRISMA.',
    remove: 'Remover',

    // Triagem
    noDataset:
      'Importe na aba Informações Principais os arquivos exportados das bases com a sua string de busca. A triagem trabalha sobre a base ativa, já deduplicada.',
    goToImport: 'Ir para a importação',
    stageTitleAbstract: 'Título e resumo',
    stageFullText: 'Texto completo',
    filterLabel: 'Mostrar',
    filters: {
      pending: 'Pendentes',
      include: 'Incluídos',
      maybe: 'Talvez',
      exclude: 'Excluídos',
      'not-retrieved': 'Não recuperados',
      all: 'Todos',
    },
    searchRecords: 'Filtrar por título, autor ou DOI',
    progress: '{done} de {total} triados',
    fullTextLocked:
      'Nenhum registro chegou ao texto completo ainda. Inclua (ou marque como "talvez") registros na triagem por título e resumo.',
    emptyList: 'Nenhum registro neste filtro.',
    allDone: 'Todos os registros desta etapa foram triados.',
    include: 'Incluir',
    exclude: 'Excluir',
    maybe: 'Talvez',
    notRetrieved: 'Não recuperado',
    clear: 'Desfazer decisão',
    reason: 'Motivo da exclusão',
    reasonOptional: 'Motivo (opcional)',
    reasonRequired: 'Escolha o motivo da exclusão — o PRISMA 2020 pede os motivos nesta etapa.',
    noCriteria: 'Sem critérios de exclusão no protocolo. Cadastre-os para registrar os motivos.',
    noReason: 'Motivo não informado',
    note: 'Nota',
    notePlaceholder: 'Observação sobre este registro (opcional)',
    noAbstract: 'Sem resumo na base.',
    openDoi: 'Abrir DOI',
    shortcuts: 'Atalhos',
    shortcutsTa: 'I incluir · E excluir · T talvez · J/K ou ↓/↑ navegar · U desfazer',
    shortcutsFt: 'I incluir · E excluir · N não recuperado · J/K ou ↓/↑ navegar · U desfazer',
    decisionLabels: {
      include: 'Incluído',
      exclude: 'Excluído',
      maybe: 'Talvez',
      'not-retrieved': 'Não recuperado',
      pending: 'Pendente',
    } as Record<string, string>,
    recordOf: 'Registro {n} de {total}',

    // PRISMA
    flowTitle: 'Fluxo PRISMA 2020',
    identification: 'Identificação',
    screening: 'Triagem',
    included: 'Incluídos',
    identifiedFrom: 'Registros identificados nas bases',
    duplicatesRemoved: 'Duplicatas removidas antes da triagem',
    recordsScreened: 'Registros triados (título e resumo)',
    recordsExcluded: 'Registros excluídos',
    reportsSought: 'Relatos buscados para recuperação',
    reportsNotRetrieved: 'Relatos não recuperados',
    reportsAssessed: 'Relatos avaliados para elegibilidade',
    reportsExcluded: 'Relatos excluídos',
    studiesIncluded: 'Estudos incluídos na revisão',
    pendingWarning:
      'A triagem não terminou: {ta} registro(s) pendente(s) em título e resumo e {ft} no texto completo. As contagens abaixo refletem o que já foi decidido.',
    dedupHint:
      'As duplicatas vêm da deduplicação aplicada na aba Informações Principais. Sem deduplicação, registros repetidos entram na triagem.',
    exportTitle: 'Exportar',
    exportPrisma: 'Arquivo para o PRISMALab (.json)',
    exportPrismaHint:
      'O PRISMALab, do ecossistema Scientata, desenha o diagrama PRISMA 2020 a partir deste arquivo: abra o PRISMALab e importe o .json.',
    openPrismaLab: 'Abrir o PRISMALab',
    exportDecisions: 'Planilha de decisões (.csv)',
    exportDecisionsHint: 'Uma linha por registro, com as decisões, os motivos e as notas das duas etapas.',
    exportIncluded: 'Estudos incluídos (.csv)',

    // Planejamento da qualidade e da extração
    qualityChecklist: 'Checklist de avaliação da qualidade',
    qualityChecklistHint:
      'Perguntas aplicadas a cada estudo incluído. Cada resposta tem um peso; a nota do estudo é a soma dos pesos.',
    qualityOptional: 'Em revisões de escopo a avaliação de qualidade é opcional.',
    qualityQuestionPlaceholder: 'Pergunta de qualidade (ex.: Os objetivos estão claramente descritos?)',
    addQualityQuestion: 'Adicionar pergunta',
    answersLabel: 'Respostas e pesos',
    answerPlaceholder: 'Resposta',
    weight: 'Peso',
    addAnswer: 'Adicionar resposta',
    cutoffLabel: 'Nota de corte',
    cutoffHint: 'Nota mínima, de {max} possíveis. Deixe em branco para não usar.',
    excludeBelowCutoff: 'Excluir da seleção final os estudos abaixo da nota de corte',
    extractionForm: 'Formulário de extração de dados',
    extractionFormHint: 'Campos preenchidos para cada estudo incluído. Campos de escolha viram gráficos na síntese.',
    fieldPlaceholder: 'Nome do campo (ex.: País do estudo)',
    fieldTypes: {
      text: 'Texto',
      number: 'Número',
      boolean: 'Sim / Não',
      date: 'Data',
      select: 'Escolha única',
      multiselect: 'Múltipla escolha',
    } as Record<string, string>,
    optionsPlaceholder: 'Adicionar opção e Enter',
    addField: 'Adicionar campo',

    // Qualidade e extração
    noIncluded:
      'Nenhum estudo incluído ainda. Inclua estudos na etapa de texto completo da triagem para avaliá-los aqui.',
    noChecklist: 'Defina as perguntas e respostas do checklist de qualidade no protocolo.',
    noForm: 'Defina os campos do formulário de extração no protocolo.',
    editInProtocol: 'Editar no protocolo',
    studyFilters: { pending: 'Pendentes', done: 'Concluídos', all: 'Todos' } as Record<string, string>,
    studyOf: 'Estudo {n} de {total}',
    studyProgress: '{done} de {total} concluídos',
    abstractLabel: 'Resumo',
    assessedComplete: 'Avaliação completa',
    score: 'Nota',
    passes: 'Passa na nota de corte',
    fails: 'Abaixo da nota de corte',
    incomplete: 'Avaliação incompleta',
    clearAnswer: 'Limpar resposta',
    markDone: 'Marcar extração como concluída',
    markedDone: 'Extração concluída',
    reopen: 'Reabrir',
    yes: 'Sim',
    no: 'Não',
    selectPlaceholder: 'Selecione…',
    previous: 'Anterior',
    next: 'Próximo',

    // Síntese
    synthesisIntro:
      'Resumo dos estudos da seleção final: características extraídas, qualidade e distribuição no tempo.',
    finalSelection: 'Seleção final',
    assessed: 'Avaliados',
    meanScore: 'Nota média',
    passing: 'Passam na nota de corte',
    extracted: 'Extração concluída',
    byYear: 'Estudos por ano',
    fieldsSummary: 'Resumo dos campos de extração',
    filledIn: '{n} de {total} preenchidos',
    numericSummary: 'média {mean} · mín. {min} · máx. {max}',
    characteristicsTable: 'Tabela de características dos estudos',
    qualityTable: 'Avaliação de qualidade por estudo',
    exportCsv: 'CSV',
    study: 'Estudo',
    qualityReason: 'Qualidade abaixo da nota de corte',
    reportTitle: 'Relatório da revisão',
    reportHint:
      'Documento Word com o protocolo, a estratégia de busca, o fluxo PRISMA, a qualidade e as características dos estudos incluídos.',
    downloadReport: 'Baixar relatório (.docx)',
    generating: 'Gerando…',
  },
  en: {
    eyebrow: 'Systematized review',
    intro:
      'Plan the protocol, screen the imported dataset in two stages, assess quality and extract data from the included studies, then produce the synthesis, the PRISMA flow and the report. Everything is saved in the project, in your browser.',
    steps: {
      protocol: 'Protocol',
      screening: 'Screening',
      quality: 'Quality',
      extraction: 'Extraction',
      synthesis: 'Synthesis',
      prisma: 'PRISMA & report',
    },

    typeLabel: 'Review type',
    types: {
      systematic: 'Systematic review',
      scoping: 'Scoping review',
      integrative: 'Integrative review',
      rapid: 'Rapid review',
      umbrella: 'Umbrella review',
      mapping: 'Systematic mapping study',
      other: 'Other systematized review',
    } satisfies Record<ReviewType, string>,
    typeHints: {
      systematic: 'Focused question, exhaustive search, quality appraisal of studies and synthesis.',
      scoping: 'Maps the extent and nature of the evidence; quality appraisal is optional.',
      integrative: 'Combines experimental and non-experimental studies to understand a phenomenon.',
      rapid: 'Streamlined steps to answer on a short deadline, with the shortcuts reported.',
      umbrella: 'Review of reviews: synthesizes existing systematic reviews.',
      mapping: 'Classifies the literature of a broad field, common in software engineering.',
      other: 'Another format with an explicit, reproducible method.',
    } satisfies Record<ReviewType, string>,
    guideline: 'Suggested reporting guideline',
    titleLabel: 'Review title',
    titlePlaceholder: 'e.g. Telehealth for older adults with chronic diseases',
    objectiveLabel: 'Objective',
    objectivePlaceholder: 'What the review aims to answer or map',
    frameworkLabel: 'Question framework',
    frameworks: {
      PICO: 'PICO',
      PICOC: 'PICOC',
      PCC: 'PCC',
      SPIDER: 'SPIDER',
      none: 'None',
    } satisfies Record<Framework, string>,
    frameworkFields: {
      population: 'Population',
      intervention: 'Intervention',
      comparison: 'Comparison',
      outcome: 'Outcome',
      context: 'Context',
      concept: 'Concept',
      sample: 'Sample',
      phenomenon: 'Phenomenon of interest',
      design: 'Design',
      evaluation: 'Evaluation',
      researchType: 'Research type',
    } as Record<string, string>,
    questionsLabel: 'Research questions',
    questionPlaceholder: 'Research question',
    addQuestion: 'Add question',
    conceptsLabel: 'Search concepts and synonyms',
    conceptsHint:
      'Synonyms of a concept are joined with OR; concepts with each other, with AND. Separate terms with a comma or Enter. Use * as a wildcard (e.g. telemedicin*).',
    conceptLabelPlaceholder: 'Concept (e.g. Population)',
    termsPlaceholder: 'Add a term and press Enter',
    addConcept: 'Add concept',
    removeTerm: 'Remove term',
    searchStringLabel: 'Search string per database',
    searchStringEmpty: 'Add concepts with terms to generate the string.',
    genericTarget: 'Generic',
    copy: 'Copy',
    copied: 'Copied',
    criteriaLabel: 'Eligibility criteria',
    inclusion: 'Inclusion',
    exclusion: 'Exclusion',
    criterionPlaceholder: 'Describe the criterion',
    addInclusion: 'Inclusion criterion',
    addExclusion: 'Exclusion criterion',
    exclusionHint: 'Exclusion criteria become the exclusion reasons in screening and in the PRISMA diagram.',
    remove: 'Remove',

    noDataset:
      'Import, in the Main Information tab, the files exported from the databases with your search string. Screening works on the active, deduplicated dataset.',
    goToImport: 'Go to import',
    stageTitleAbstract: 'Title & abstract',
    stageFullText: 'Full text',
    filterLabel: 'Show',
    filters: {
      pending: 'Pending',
      include: 'Included',
      maybe: 'Maybe',
      exclude: 'Excluded',
      'not-retrieved': 'Not retrieved',
      all: 'All',
    },
    searchRecords: 'Filter by title, author or DOI',
    progress: '{done} of {total} screened',
    fullTextLocked:
      'No record has reached full text yet. Include (or mark as "maybe") records in the title and abstract screening.',
    emptyList: 'No records in this filter.',
    allDone: 'Every record in this stage has been screened.',
    include: 'Include',
    exclude: 'Exclude',
    maybe: 'Maybe',
    notRetrieved: 'Not retrieved',
    clear: 'Undo decision',
    reason: 'Exclusion reason',
    reasonOptional: 'Reason (optional)',
    reasonRequired: 'Pick the exclusion reason — PRISMA 2020 asks for reasons at this stage.',
    noCriteria: 'No exclusion criteria in the protocol. Add them to record the reasons.',
    noReason: 'Reason not given',
    note: 'Note',
    notePlaceholder: 'Remark about this record (optional)',
    noAbstract: 'No abstract in the dataset.',
    openDoi: 'Open DOI',
    shortcuts: 'Shortcuts',
    shortcutsTa: 'I include · E exclude · T maybe · J/K or ↓/↑ navigate · U undo',
    shortcutsFt: 'I include · E exclude · N not retrieved · J/K or ↓/↑ navigate · U undo',
    decisionLabels: {
      include: 'Included',
      exclude: 'Excluded',
      maybe: 'Maybe',
      'not-retrieved': 'Not retrieved',
      pending: 'Pending',
    } as Record<string, string>,
    recordOf: 'Record {n} of {total}',

    flowTitle: 'PRISMA 2020 flow',
    identification: 'Identification',
    screening: 'Screening',
    included: 'Included',
    identifiedFrom: 'Records identified from databases',
    duplicatesRemoved: 'Duplicates removed before screening',
    recordsScreened: 'Records screened (title & abstract)',
    recordsExcluded: 'Records excluded',
    reportsSought: 'Reports sought for retrieval',
    reportsNotRetrieved: 'Reports not retrieved',
    reportsAssessed: 'Reports assessed for eligibility',
    reportsExcluded: 'Reports excluded',
    studiesIncluded: 'Studies included in the review',
    pendingWarning:
      'Screening is not finished: {ta} pending record(s) in title and abstract and {ft} in full text. The counts below reflect what has been decided so far.',
    dedupHint:
      'Duplicates come from the deduplication applied in the Main Information tab. Without deduplication, repeated records go to screening.',
    exportTitle: 'Export',
    exportPrisma: 'File for PRISMALab (.json)',
    exportPrismaHint:
      'PRISMALab, part of the Scientata ecosystem, draws the PRISMA 2020 diagram from this file: open PRISMALab and import the .json.',
    openPrismaLab: 'Open PRISMALab',
    exportDecisions: 'Decisions spreadsheet (.csv)',
    exportDecisionsHint: 'One row per record, with the decisions, reasons and notes of both stages.',
    exportIncluded: 'Included studies (.csv)',

    qualityChecklist: 'Quality assessment checklist',
    qualityChecklistHint:
      'Questions applied to each included study. Every answer has a weight; the study score is the sum of the weights.',
    qualityOptional: 'In scoping reviews quality assessment is optional.',
    qualityQuestionPlaceholder: 'Quality question (e.g. Are the aims clearly stated?)',
    addQualityQuestion: 'Add question',
    answersLabel: 'Answers and weights',
    answerPlaceholder: 'Answer',
    weight: 'Weight',
    addAnswer: 'Add answer',
    cutoffLabel: 'Cutoff score',
    cutoffHint: 'Minimum score, out of {max}. Leave empty to not use one.',
    excludeBelowCutoff: 'Exclude studies below the cutoff from the final selection',
    extractionForm: 'Data extraction form',
    extractionFormHint: 'Fields filled in for each included study. Choice fields become charts in the synthesis.',
    fieldPlaceholder: 'Field name (e.g. Study country)',
    fieldTypes: {
      text: 'Text',
      number: 'Number',
      boolean: 'Yes / No',
      date: 'Date',
      select: 'Single choice',
      multiselect: 'Multiple choice',
    } as Record<string, string>,
    optionsPlaceholder: 'Add an option and press Enter',
    addField: 'Add field',

    noIncluded: 'No included studies yet. Include studies in the full-text screening stage to assess them here.',
    noChecklist: 'Define the quality checklist questions and answers in the protocol.',
    noForm: 'Define the extraction form fields in the protocol.',
    editInProtocol: 'Edit in the protocol',
    studyFilters: { pending: 'Pending', done: 'Done', all: 'All' } as Record<string, string>,
    studyOf: 'Study {n} of {total}',
    studyProgress: '{done} of {total} done',
    abstractLabel: 'Abstract',
    assessedComplete: 'Assessment complete',
    score: 'Score',
    passes: 'Meets the cutoff',
    fails: 'Below the cutoff',
    incomplete: 'Assessment incomplete',
    clearAnswer: 'Clear answer',
    markDone: 'Mark extraction as done',
    markedDone: 'Extraction done',
    reopen: 'Reopen',
    yes: 'Yes',
    no: 'No',
    selectPlaceholder: 'Select…',
    previous: 'Previous',
    next: 'Next',

    synthesisIntro: 'Summary of the studies in the final selection: extracted characteristics, quality and distribution over time.',
    finalSelection: 'Final selection',
    assessed: 'Assessed',
    meanScore: 'Mean score',
    passing: 'Meet the cutoff',
    extracted: 'Extraction done',
    byYear: 'Studies per year',
    fieldsSummary: 'Extraction fields summary',
    filledIn: '{n} of {total} filled in',
    numericSummary: 'mean {mean} · min {min} · max {max}',
    characteristicsTable: 'Characteristics of the studies',
    qualityTable: 'Quality assessment per study',
    exportCsv: 'CSV',
    study: 'Study',
    qualityReason: 'Quality below the cutoff',
    reportTitle: 'Review report',
    reportHint:
      'Word document with the protocol, search strategy, PRISMA flow, quality and characteristics of the included studies.',
    downloadReport: 'Download report (.docx)',
    generating: 'Generating…',
  },
};

export type ReviewCopy = (typeof REVIEW_COPY)['pt'];
